baseURL = "https://iamanuragh.in/"
languageCode = "en-us"
title = "Welcome"
theme="hugo-theme-nix"
[params]
  Name = "Anuragh KP"
  HeaderUsername = "0x55aa"
  HeaderHostname = "boot"
  About = "I like technology and pretty much all beautiful stuff in the world, Every time try to learn some new things. This page also the result of learning 😅"
  ProfilePicture = "https://avatars2.githubusercontent.com/u/36616831?s=460&v=4"
  BitbucketID = "0xaa55_boot"
  Email = "kpanuragh@gmail.com"
  FacebookID = "kpanuragh"
  GithubID = "kpanuragh"
  GitlabId = "Anuraghkp"
  GnuPGFingerprint = "1E8ABFF52BECD769990816A540C963A0F8113954"
  InstagramID = "anuraghkp"
  LinkedInID = "anuraghkp"
  StackExchangeID = "13088745"
  StackOverflowID = "9456940"
  TwitterID = "@anuragh_kp"

